### ISSUE TITLE
CodeBuild & CodePipeline

### ISSUE THREAD

**Issue by daaku** [nzoschke/gofaas#27]
Might be nice to use CodeBuild & CodePipeline for the deployment process and have it be setup as part of the CF template.

**Comment by nzoschke** [comment]
This could be a nice addition. I'm also looking into CodeDeploy to facilitate more canary deployments as explained here:

https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst

**Comment by nzoschke** [comment]
After more thought I don't plan to add CodeBulid or CodePipeline in the project myself any time soon.

This project is more about the why and how to use FaaS services. Build / deploy services and workflows are orthogonal to that.
